services:
  - type: web
    name: ipms
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DEMO_MODE
        value: "true"
      - key: NODE_ENV
        value: production
      - key: DIST_PATH
        value: ./frontend/dist
      - key: DB_PATH
        value: /tmp/ipms.db
